module.exports = {
  C01 : { display : true , name : 'Raum-Soll'                         },
  C02 : { display : true , name : 'Raum-Ist'                          },
  C03 : { display : true , name : 'Boiler-Soll'                       },
  C04 : { display : true , name : 'Boiler-Ist'                        },
  C05 : { display : true , name : 'Vorlauf-Soll'                      },
  C06 : { display : true , name : 'Volauf-Ist'                        },
  C07 : { display : true , name : 'Aktuelle Außentemp.'               },
  C08 : { display : true , name : 'Aktuelle Grundwassert.'            },
  C09 : { display : true , name : 'Aktuelle Puffert.'                 },
  C10 : { display : true , name : 'Betriebst. Wärmep. 1 & 2'          },
  C11 : { display : true , name : 'Einstellungen in Menüs'            },
  C12 : { display : true , name : 'Aktuelle Grundwassert.'            },

  F01 : { display : true , name : 'Err Temp.sensor'                   },
  F02 : { display : true , name : 'Err Stroemung'                     },
  F03 : { display : true , name : 'Err Waermepumpe'                   },

  M01 : { display : true , name : 'T-Vorlauf'                         },
  M02 : { display : true , name : 'T-Sole'                            },
  M03 : { display : true , name : 'T-Aussen'                          },
  M04 : { display : true , name : 'T-Raum'                            },
  M05 : { display : true , name : 'T-Puffer'                          },
  M06 : { display : true , name : 'T-Boiler'                          },
  M07 : { display : true , name : 'T-WP2'                             },
  M08 : { display : true , name : 'T-WP1'                             },
  M09 : { display : true , name : 'T-Reserv1'                         },
  M10 : { display : true , name : 'T-Reserv2'                         },
  M11 : { display : true , name : 'T-Raumsoll'                        },
  M12 : { display : true , name : 'T-Vorlauf2'                        },
  M13 : { display : true , name : 'T-Sole2'                           },
  M14 : { display : true , name : 'Pt1000 WP1'                        },
  M15 : { display : true , name : 'Pt1000 WP2'                        },
  M16 : { display : true , name : 'Steps WP1'                         },
  M17 : { display : true , name : 'Steps WP2'                         },
  M18 : { display : true , name : 'Codier WP1'                        },
  M19 : { display : true , name : 'Codier WP2'                        },

  I01 : { display : true , name : 'Sicherungskette'                   },
  I02 : { display : true , name : 'Sperre Heizen'                     },
  I03 : { display : true , name : 'Sperre Boiler'                     },
  I04 : { display : true , name : 'DruckschalterWP1'                  },
  I05 : { display : true , name : 'DruckschalterWP2'                  },
  I06 : { display : true , name : 'Niederdruck-WP1'                   },
  I07 : { display : true , name : 'Reserve E.E.8'                     },
  I08 : { display : true , name : 'Niederdruck-WP2'                   },
  I09 : { display : true , name : 'Stroemung-WP1'                     },
  I10 : { display : true , name : 'Stroemung-WP2'                     },
  I11 : { display : true , name : 'Sperre Raumbed.g'                  },

  O01 : { display : true , name : 'UP Heizung'                        },
  O02 : { display : true , name : 'UP Grundwasser'                    },
  O03 : { display : true , name : 'WP1 laeuft'                        },
  O04 : { display : true , name : 'WP2 laeuft'                        },
  O05 : { display : true , name : 'UP Boiler'                         },
  O06 : { display : true , name : 'UP1 Mischer'                       },
  O07 : { display : true , name : 'Reserve A.E.7'                     },
  O08 : { display : true , name : 'UP2 Mischer'                       },
  O09 : { display : true , name : 'Mischer1 Auf'                      },
  O10 : { display : true , name : 'Mischer1 Zu'                       },
  O11 : { display : true , name : 'Mischer2 Auf'                      },
  O12 : { display : true , name : 'Mischer2 Zu'                       },
  O13 : { display : true , name : 'Fernstoerung'                      },
  O14 : { display : true , name : 'Reserve A.E.14'                    },
  O15 : { display : true , name : 'Reserve A.E.15'                    },

  E01A: { display : true , name : 'Temperaturfühler'                  },
  E01B: { display : true , name : 'Umwälzpumpe1 Heizung'              },
  E01C: { display : true , name : 'Umwälzpumpe2 Boiler/Puffer'        },
  E01D: { display : true , name : 'Umwälzpumpe Grundwasser/Sole'      },
  E01E: { display : true , name : 'Strömungswächter'                  },
  E01F: { display : true , name : 'Wärmepumpe1'                       },
  E01G: { display : true , name : 'Wärmepumpe2'                       },

  E02A: { display : true , name : 'Vorlauffühler fehlt'               },
  E02B: { display : true , name : 'Solefühler fehlt'                  },
  E02C: { display : true , name : 'Außenfühler fehlt'                 },
  E02D: { display : true , name : 'Raumfühler fehlt'                  },
  E02E: { display : true , name : 'Pufferfühler fehlt'                },
  E02F: { display : true , name : 'Boilerfühler fehlt'                },
  E02G: { display : true , name : 'Verd.fühlerWP1 fehlt'              },
  E02H: { display : true , name : 'Verd.fühlerWP2 fehlt'              },

  E03A: { display : true , name : 'SWE 1 immer aus'                   },
  E03B: { display : true , name : 'SWE 2 immer aus'                   },
  E03C: { display : true , name : 'SWE 1 immer ein'                   },
  E03D: { display : true , name : 'SWE 2 immer ein'                   },
  E03E: { display : true , name : 'GW Vorrat WP 1'                    },
  E03F: { display : true , name : 'GW Vorrat WP 2'                    },

  E04A: { display : true , name : 'Pressostat WP1'                    },
  E04B: { display : true , name : 'Pressostat WP2'                    },
  E04C: { display : true , name : 'Sole/GW zu kalt'                   },
  E04D: { display : true , name : 'SI-Kette/ Thermorel.'              },
  E04E: { display : true , name : 'Hochdruck WP1'                     },
  E04F: { display : true , name : 'Hochdruck WP2'                     },
  E04G: { display : true , name : 'Verdampfungtemp. WP1'              },
  E04H: { display : true , name : 'Verdampfungtemp. WP2'              },
};
